Table ParkAreas {
    id integer [PK]
    areaName varchar
    location varchar
}

Table Services {
    id integer [PK]
    serviceName varchar
}

Table Guests {
    id integer [PK]
    firstName varchar
    lastName varchar
    areaId integer
}

Table AreaServices {
    areaServices integer [PK]
    serviceId integer
    areaId integer
}

Ref: Services.id < AreaServices.serviceId  
Ref: ParkAreas.id < AreaServices.areaId

Ref: Guests.areaId > ParkAreas.id